import { afterAll, beforeEach, describe, expect, it } from 'vitest';
import { GymStatus } from '@fit/db';
import { InvoiceService, type IssueInvoiceInput } from './invoice.service';
import { disconnect, prisma, resetDb } from '../test/integration-db';

/**
 * Invoice numbering proven against a real Postgres (T5.9): the per-gym+year sequence
 * is generated by the actual `INSERT … ON CONFLICT DO UPDATE … RETURNING` statement, so
 * this exercises what a unit spec can only fake — that numbers are sequential and
 * gap-free within a gym-year, reset each fiscal year, are isolated per gym, and stay
 * unique under concurrent charges racing for the same gym-year.
 */
const service = new InvoiceService();

/** Issue one invoice inside its own transaction, as the enrolment / billing flows do. */
function issue(input: IssueInvoiceInput) {
  return prisma.$transaction((tx) => service.issue(tx, input));
}

const charge = (gymId: string, over?: Partial<IssueInvoiceInput>): IssueInvoiceInput => ({
  gymId,
  memberId: null,
  amount: 5000,
  currency: 'USD',
  issuedAt: new Date('2026-06-01T00:00:00.000Z'),
  ...over,
});

describe('InvoiceService (integration)', () => {
  let gymAId: string;
  let gymBId: string;

  beforeEach(async () => {
    await resetDb();
    const gymA = await prisma.gym.create({
      data: { name: 'Alpha Gym', slug: 'alpha-gym', status: GymStatus.ACTIVE },
    });
    gymAId = gymA.id;
    const gymB = await prisma.gym.create({
      data: { name: 'Beta Gym', slug: 'beta-gym', status: GymStatus.ACTIVE },
    });
    gymBId = gymB.id;
  });

  afterAll(disconnect);

  it('numbers invoices sequentially per gym within a year', async () => {
    const first = await issue(charge(gymAId));
    const second = await issue(charge(gymAId));
    const third = await issue(charge(gymAId));

    expect([first.number, second.number, third.number]).toEqual([
      '2026-0001',
      '2026-0002',
      '2026-0003',
    ]);
    expect([first.seq, second.seq, third.seq]).toEqual([1, 2, 3]);
    expect(first.year).toBe(2026);
  });

  it('restarts the sequence at 0001 for a new fiscal year', async () => {
    const y2026 = await issue(charge(gymAId, { issuedAt: new Date('2026-12-31T23:00:00.000Z') }));
    const y2027 = await issue(charge(gymAId, { issuedAt: new Date('2027-01-01T00:00:00.000Z') }));

    expect(y2026.number).toBe('2026-0001');
    expect(y2027.number).toBe('2027-0001');
  });

  it('keeps each gym’s sequence independent (isolation)', async () => {
    const a1 = await issue(charge(gymAId));
    const b1 = await issue(charge(gymBId));
    const a2 = await issue(charge(gymAId));

    expect(a1.number).toBe('2026-0001');
    expect(b1.number).toBe('2026-0001');
    expect(a2.number).toBe('2026-0002');
  });

  it('hands out distinct, gap-free numbers under concurrent charges for one gym-year', async () => {
    const count = 20;
    const results = await Promise.all(Array.from({ length: count }, () => issue(charge(gymAId))));

    const seqs = results.map((r) => r.seq).sort((a, b) => a - b);
    expect(seqs).toEqual(Array.from({ length: count }, (_, i) => i + 1));

    // Every persisted number is unique — the DB's `@@unique([gymId, number])` would
    // reject a collision, so a full set proves the counter serialised correctly.
    const numbers = new Set(results.map((r) => r.number));
    expect(numbers.size).toBe(count);
    const stored = await prisma.invoice.count({ where: { gymId: gymAId } });
    expect(stored).toBe(count);
  });

  it('persists the charge details and defaults status to PAID', async () => {
    const issued = await issue(
      charge(gymAId, {
        amount: 12000,
        currency: 'GEL',
        description: 'Premium — monthly subscription',
      }),
    );

    const stored = await prisma.invoice.findUniqueOrThrow({ where: { id: issued.id } });
    expect(stored).toMatchObject({
      gymId: gymAId,
      amount: 12000,
      currency: 'GEL',
      status: 'PAID',
      description: 'Premium — monthly subscription',
      number: '2026-0001',
      year: 2026,
      seq: 1,
    });
  });
});
